/* Reference board — 48 tiles, clockwise from START.
   The purchase prices, names, locations and flags are transcribed from the
   supplied image. Side faces rotate as a unit, including their flag badges. */
const GROUP_HOUSE_COST = { BR: 50, IL: 50, IN: 100, IT: 100, DE: 100, JO: 150, FR: 150, JP: 150, GB: 200, US: 200 };
const GROUP_COLOR = {
  BR: '#6da443', IL: '#337bc2', IN: '#f3a03c', IT: '#4c9860', DE: '#cd2846',
  JO: '#dc1244', FR: '#366cc5', JP: '#b8244b', GB: '#78508f', US: '#b65073'
};
const FLAG_OF = {
  BR: '🇹🇳', IL: '🇪🇬', IN: '🇵🇸', IT: '🇲🇦', DE: '🇰🇼', JO: '🇯🇴', FR: '🇸🇾', JP: '🇦🇪', GB: '🇮🇶', US: '🇸🇦',
  KW: '🇰🇼', BH: '🇧🇭', QA: '🇶🇦'
};
const COUNTRY_NAME = {
  BR: 'Tunisia', IL: 'Egypt', IN: 'Palestine', IT: 'Morocco', DE: 'Kuwait',
  JO: 'Jordan', FR: 'Syria', JP: 'United Arab Emirates', GB: 'Iraq', US: 'Saudi Arabia',
  KW: 'Kuwait', BH: 'Bahrain', QA: 'Qatar'
};
/* Blurred-flag face artwork per country (assets/board/art/city-<iso>.png),
   generated by scripts/build_country_art.py. */
const COUNTRY_ISO = {
  Tunisia: 'tn', Egypt: 'eg', Palestine: 'ps', Morocco: 'ma', Kuwait: 'kw',
  Jordan: 'jo', Syria: 'sy', 'United Arab Emirates': 'ae', Iraq: 'iq',
  'Saudi Arabia': 'sa', Bahrain: 'bh', Qatar: 'qa'
};
const COUNTRY_ALIASES = {
  tunisia: 'BR', tunisian: 'BR', sfax: 'BR', tunis: 'BR',
  egypt: 'IL', egyptian: 'IL', cairo: 'IL', alexandria: 'IL', giza: 'IL',
  palestine: 'IN', palestinian: 'IN', halhul: 'IN', jerusalem: 'IN',
  morocco: 'IT', moroccan: 'IT', tangier: 'IT', fes: 'IT', agadir: 'IT', rabat: 'IT',
  kuwait: 'DE', kuwaiti: 'DE', hawalli: 'DE', salmiya: 'DE',
  bahrain: 'DE', bahraini: 'DE', manama: 'DE',
  qatar: 'DE', qatari: 'DE', doha: 'DE',
  jordan: 'JO', jordanian: 'JO', amman: 'JO', irbid: 'JO',
  syria: 'FR', syrian: 'FR', damascus: 'FR', aleppo: 'FR',
  uae: 'JP', emirates: 'JP', 'united arab emirates': 'JP', sharjah: 'JP', dubai: 'JP',
  iraq: 'GB', iraqi: 'GB', baghdad: 'GB', mosul: 'GB', basra: 'GB', erbil: 'GB',
  saudi: 'US', 'saudi arabia': 'US', dammam: 'US', jeddah: 'US', riyadh: 'US'
};

/* Explicit rent table per city: [base, 1 house, 2 houses, 3 houses, 4 houses, hotel].
   Supplied directly by the reference sheet — overrides the old formula-based rent. */
const RENT_TABLE = {
  Sfax: [30, 80, 120, 260, 300, 350],
  Tunis: [50, 120, 160, 240, 390, 480],
  Cairo: [80, 130, 140, 360, 450, 560],
  Alexandria: [90, 140, 160, 250, 340, 450],
  Giza: [70, 140, 260, 310, 390, 490],
  Halhul: [90, 180, 250, 360, 490, 650],
  Jerusalem: [110, 200, 360, 450, 570, 700],
  Tangier: [100, 240, 360, 450, 570, 700],
  Fes: [110, 260, 340, 400, 530, 660],
  Agadir: [140, 290, 370, 420, 570, 690],
  Rabat: [180, 300, 500, 760, 860, 950],
  'Kuwait City': [180, 370, 590, 760, 910, 1000],
  Hawalli: [180, 360, 610, 740, 950, 1100],
  Bahrain: [180, 360, 610, 740, 950, 1500],
  Qatar: [180, 360, 610, 740, 950, 1500],
  Aleppo: [180, 240, 430, 640, 760, 850],
  Damascus: [180, 230, 470, 660, 700, 800],
  Dubai: [180, 550, 900, 1000, 1550, 2500],
  Sharjah: [180, 450, 940, 1060, 1400, 2000],
  Amman: [90, 250, 360, 480, 610, 700],
  Irbid: [90, 200, 260, 380, 540, 650],
  Baghdad: [50, 20, 150, 30, 250, 400],
  Mosul: [50, 100, 50, 250, 100, 300],
  Basra: [50, 140, 80, 300, 110, 450],
  Riyadh: [180, 290, 550, 1100, 1800, 2000],
  Jeddah: [150, 260, 450, 1000, 1200, 1500],
  Dammam: [130, 240, 400, 900, 1000, 1200]
};

function city(r, c, name, cost, group, customCountry, customFlag) {
  const base = Math.round(cost / 10);
  const country = customCountry || COUNTRY_NAME[group];
  return {
    type: 'city', r, c, name, cost, price: `${cost}$`, group,
    country,
    art: 'city-' + COUNTRY_ISO[country],
    flag: customFlag || FLAG_OF[group],
    color: GROUP_COLOR[group],
    houseCost: GROUP_HOUSE_COST[group],
    // Use the explicit rent table when supplied; otherwise fall back to the old formula.
    rent: RENT_TABLE[name] || [base, base * 5, base * 15, base * 45, base * 70, base * 90]
  };
}
const airport = (r, c, name) => ({ type: 'airport', r, c, name, cost: 200, price: '200$', icon: '✈️', special: true });
const company = (r, c, name, icon, artwork) => ({ type: 'company', r, c, name, cost: 150, price: '150$', icon, artwork, special: true });
const treasure = (r, c) => ({ type: 'treasure', r, c, name: 'Treasure', icon: '🎁', special: true });
const surprise = (r, c) => ({ type: 'surprise', r, c, name: 'Surprise', icon: '❓', special: true });

const BOARD = [
  { type: 'start', r: 1, c: 1, name: 'START', corner: true, special: true },
  city(1, 2, 'Sfax', 150, 'BR'),
  treasure(1, 3),
  city(1, 4, 'Tunis', 100, 'BR'),
  { type: 'tax', r: 1, c: 5, name: 'Earnings Tax', special: true, price: '%10', taxPercent: 10, artwork: 'earnings-tax' },
  city(1, 6, 'Cairo', 210, 'IL'),
  airport(1, 7, 'CAI Airport'),
  city(1, 8, 'Alexandria', 190, 'IL'),
  city(1, 9, 'Giza', 180, 'IL'),
  surprise(1, 10),
  city(1, 11, 'Halhul', 190, 'IN'),
  city(1, 12, 'Jerusalem', 200, 'IN'),
  { type: 'jail', r: 1, c: 13, name: 'In Prison', corner: true, special: true },
  city(2, 13, 'Tangier', 180, 'IT'),
  city(3, 13, 'Fes', 150, 'IT'),
  company(4, 13, 'Power Company', '⚡', 'power'),
  city(5, 13, 'Agadir', 160, 'IT'),
  city(6, 13, 'Rabat', 200, 'IT'),
  airport(7, 13, 'CMN Airport'),
  city(8, 13, 'Kuwait City', 250, 'DE', 'Kuwait', '🇰🇼'),
  treasure(9, 13),
  city(10, 13, 'Bahrain', 650, 'DE', 'Bahrain', '🇧🇭'),
  company(11, 13, 'Gas Company', '🔥', 'gas'),
  city(12, 13, 'Qatar', 600, 'DE', 'Qatar', '🇶🇦'),
  { type: 'vacation', r: 13, c: 13, name: 'Vacation', corner: true, special: true },
  city(13, 12, 'Aleppo', 190, 'FR'),
  city(13, 11, 'Damascus', 200, 'FR'),
  city(13, 10, 'Dubai', 350, 'JP'),
  city(13, 9, 'Sharjah', 300, 'JP'),
  surprise(13, 8),
  airport(13, 7, 'ALP Airport'),
  surprise(13, 6),
  treasure(13, 5),
  company(13, 4, 'Water Company', '💧', 'water'),
  city(13, 3, 'Amman', 250, 'JO'),
  city(13, 2, 'Irbid', 280, 'JO'),
  { type: 'gotojail', r: 13, c: 1, name: 'Go to prison', corner: true, special: true },
  city(12, 1, 'Baghdad', 190, 'GB'),
  city(11, 1, 'Mosul', 160, 'GB'),
  treasure(10, 1),
  city(9, 1, 'Basra', 120, 'GB'),
  city(8, 1, 'Hawalli', 280, 'GB', 'Kuwait', '🇰🇼'),
  airport(7, 1, 'RUH Airport'),
  city(6, 1, 'Dammam', 330, 'US'),
  surprise(5, 1),
  city(4, 1, 'Jeddah', 380, 'US'),
  { type: 'tax', r: 3, c: 1, name: 'Premium Tax', special: true, price: '$75', taxFlat: 75, artwork: 'premium-tax' },
  city(2, 1, 'Riyadh', 410, 'US')
];

const IDX_START = 0;
const IDX_JAIL = 12;
const IDX_VACATION = 24;
const IDX_GOTOJAIL = 36;
const AIRPORT_IDS = BOARD.map((t, i) => t.type === 'airport' ? i : -1).filter(i => i >= 0);
const COMPANY_IDS = BOARD.map((t, i) => t.type === 'company' ? i : -1).filter(i => i >= 0);
function groupTiles(group) { return BOARD.map((tile, i) => tile.group === group ? i : -1).filter(i => i >= 0); }
